modified buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -2,36 +2,39 @@ version: 0.2
  
 env:
   variables:
-    ACTION: "plan"   # default (can be overridden in CodeBuild)
+    ACTION: "plan"   # default (will override in pipeline)
  
 phases:
   install:
     commands:
-      - echo "Installing Terraform..."
-      - yum install -y unzip
-      - curl -O https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
-      - unzip terraform_1.6.0_linux_amd64.zip
+      - echo "Installing Terraform"
+      - curl -LO https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
+      - unzip terraform_1.5.7_linux_amd64.zip
       - mv terraform /usr/local/bin/
-      - terraform --version
  
   pre_build:
     commands:
-      - echo "Initializing Terraform..."
-      - terraform init -reconfigure
+      - echo "Terraform Init"
+      - terraform init
  
   build:
     commands:
-      - echo "Running Terraform action: $ACTION"
+      - echo "Action is $ACTION"
  
       - |
-        if [ "$ACTION" = "apply" ]; then
-          echo "Applying infrastructure..."
+        if [ "$ACTION" = "plan" ]; then
+          echo "Running Terraform Plan"
+          terraform plan -out=tfplan
+ 
+        elif [ "$ACTION" = "apply" ]; then
+          echo "Running Terraform Apply"
           terraform apply -auto-approve
+ 
         else
-          echo "Running plan..."
-          terraform plan
+          echo "Invalid ACTION"
+          exit 1
         fi
  
-  post_build:
-    commands:
-      - echo "Build completed successfully"
+artifacts:
+  files:
+    - '**/*'
